"""rename calendar job fields

Revision ID: 00c6e2f556a3
Revises: 580690bfb0f8
Create Date: 2026-07-02 20:13:08.609950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c6e2f556a3'
down_revision: Union[str, Sequence[str], None] = '580690bfb0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_jobs', sa.Column('module', sa.String(length=50), nullable=False))
    op.add_column('calendar_jobs', sa.Column('target_period', sa.String(length=20), nullable=False))
    op.drop_column('calendar_jobs', 'period')
    op.drop_column('calendar_jobs', 'job_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_jobs', sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('calendar_jobs', sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('calendar_jobs', 'target_period')
    op.drop_column('calendar_jobs', 'module')
    # ### end Alembic commands ###
