"""first

Revision ID: 56de6f60a228
Revises: 
Create Date: 2026-05-04 18:29:10.500267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56de6f60a228'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ezmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_ymd', sa.String(length=8), nullable=False),
    sa.Column('od', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.Column('prosrochka_1', sa.Numeric(precision=20, scale=2), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ezmes')
    # ### end Alembic commands ###
