"""add calendar jobs

Revision ID: 580690bfb0f8
Revises: f5893a050325
Create Date: 2026-07-02 20:06:21.666710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580690bfb0f8'
down_revision: Union[str, Sequence[str], None] = 'f5893a050325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('segment_id', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('base_ymd', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='waiting', nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('next_check_at', sa.DateTime(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_jobs')
    # ### end Alembic commands ###
