"""add forecast models

Revision ID: a27abd17699d
Revises: 00c6e2f556a3
Create Date: 2026-07-03 09:19:39.011155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27abd17699d'
down_revision: Union[str, Sequence[str], None] = '00c6e2f556a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_code', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('forecast_type', sa.String(length=50), nullable=False),
    sa.Column('segment_id', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_models')
    # ### end Alembic commands ###
