"""add segment id to ezmes

Revision ID: b9f1f9ad5f49
Revises: c39684d84525
Create Date: 2026-07-03 11:08:11.698481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f1f9ad5f49'
down_revision: Union[str, Sequence[str], None] = 'c39684d84525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ezmes', sa.Column('segment_id', sa.String(length=50), server_default='retail', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ezmes', 'segment_id')
    # ### end Alembic commands ###
