"""add forecast model versions

Revision ID: c39684d84525
Revises: cb2b12fca3cc
Create Date: 2026-07-03 09:26:22.937095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39684d84525'
down_revision: Union[str, Sequence[str], None] = 'cb2b12fca3cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['forecast_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_model_versions')
    # ### end Alembic commands ###
