"""add forecast models

Revision ID: cb2b12fca3cc
Revises: a27abd17699d
Create Date: 2026-07-03 09:22:38.290706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2b12fca3cc'
down_revision: Union[str, Sequence[str], None] = 'a27abd17699d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_models', sa.Column('algorithm', sa.String(length=100), nullable=False))
    op.add_column('forecast_models', sa.Column('parameters_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_models', 'parameters_json')
    op.drop_column('forecast_models', 'algorithm')
    # ### end Alembic commands ###
