"""add forecast run tables

Revision ID: f5893a050325
Revises: 56de6f60a228
Create Date: 2026-07-02 16:18:23.804429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5893a050325'
down_revision: Union[str, Sequence[str], None] = '56de6f60a228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_type', sa.String(length=50), nullable=False),
    sa.Column('segment_id', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('horizon_months', sa.Integer(), server_default='3', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('forecast_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fact_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('abs_error', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pct_error', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='planned', nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_values')
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
